website = "https://github.com/RavindraTirlangi/Klyro"
add_all_files = "https://github.com/RavindraTirlangi/Klyro"
edit_errors = "https://github.com/RavindraTirlangi/Klyro"
git = "https://github.com/RavindraTirlangi/Klyro"
enable_playwright = "https://github.com/RavindraTirlangi/Klyro"
favicon = (
    "https://github.com/RavindraTirlangi/Klyro/blob/main/"
    "klyro/website/assets/icons/favicon-32x32.png"
)
model_warnings = "https://github.com/RavindraTirlangi/Klyro"
token_limits = "https://github.com/RavindraTirlangi/Klyro"
llms = "https://github.com/RavindraTirlangi/Klyro"
large_repos = "https://github.com/RavindraTirlangi/Klyro"
github_issues = "https://github.com/RavindraTirlangi/Klyro/issues/new"
git_index_version = "https://github.com/RavindraTirlangi/Klyro/issues/211"
install_properly = "https://github.com/RavindraTirlangi/Klyro"
analytics = "https://github.com/RavindraTirlangi/Klyro"
release_notes = "https://github.com/RavindraTirlangi/Klyro/blob/main/HISTORY.md"
edit_formats = "https://github.com/RavindraTirlangi/Klyro"
models_and_keys = "https://github.com/RavindraTirlangi/Klyro"
